name: Update Dependency Version

on:
  repository_dispatch:
    types: [dependency_update]

jobs:
  update-gradle-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update math-utils-library dependency version
        run: |
            VERSION=${{ github.event.client_payload.version }}
            echo "Updating math-utils-library version to $VERSION"
            sed -i -E "s|(implementation ['\"]com\.example\.Sadiq-Chigur:math-utils-library:)[^'\"]*(['\"])|\1$VERSION\2|" build.gradle
            echo "Updated line:"
            grep "math-utils-library" build.gradle || echo "No match found!"

      - name: Commit and push changes
        run: |
            VERSION=${{ github.event.client_payload.version }}
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b update-math-utils-$VERSION || git checkout update-math-utils-$VERSION
            git add build.gradle
            if git diff --cached --quiet; then
            echo "No changes to commit."
            else
            git commit -m "Update math-utils-library to version $VERSION"
            git push origin update-math-utils-$VERSION
            fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-math-utils-${{ github.event.client_payload.version }}
          base: main
          title: "Update math-utils-library to version ${{ github.event.client_payload.version }}"
          body: |
            This automated PR updates the math-utils-library dependency to version **${{ github.event.client_payload.version }}**.
